remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Juan's Capstone Project
description: Weekly Updates from my capstone project
